{% set name = "imodels" %}
{% set version = "2.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imodels-{{ version }}.tar.gz
  sha256: 6aadab17ff176033022264a70c3571fa300bd2584590aec80bbf0254d91f58ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >={{ python_min }}
    - setuptools >=64
    - wheel
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - mlxtend
    - numpy
    - pandas
    - requests
    - scikit-learn
    - scipy
    - tqdm

test:
  imports:
    - imodels
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/csinva/imodels
  summary: Implementations of various interpretable models
  description: |
    imodels provides a simple interface for fitting and using state-of-the-art
    interpretable models -- rule sets, rule lists and trees -- all compatible
    with scikit-learn.
  license: MIT
  license_file: license.md
  doc_url: https://csinva.io/imodels/
  dev_url: https://github.com/csinva/imodels

extra:
  recipe-maintainers:
    - csinva
