"""Render the hand-written docs pages from a shared template.

`figs.html`, `shrinkage.html`, `mdi_plus.html` and `gpgam.html` are written by
hand rather than generated by pdoc, so they used to carry their own copy of the
page shell -- and those copies drifted apart, each ending up with a different
subset of the sidebar links.

This script keeps one source of truth. The shell (stylesheets, scripts, and the
whole left-hand sidebar) is lifted straight out of the generated `index.html`,
so the sub-pages always show exactly what the index shows. Only the article body
of each page lives in `pages/<name>.html`; everything around it comes from here.

Run it after pdoc has produced index.html -- `build_docs.sh` does this for you:

    uv run python build_pages.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

# title, plus any page-specific <head> additions
PAGES = {
    "figs": (
        "FIGS",
        '    <script src="https://cdn.plot.ly/plotly-2.6.3.min.js"></script>\n'
        "    <script type=\"text/javascript\">window.PlotlyConfig = { MathJaxConfig: 'local' };</script>\n",
    ),
    "shrinkage": (
        "Hierarchical shrinkage",
        '    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>\n'
        '    <script src="https://cdn.plot.ly/plotly-2.6.3.min.js"></script>\n'
        "    <script type=\"text/javascript\">window.PlotlyConfig = { MathJaxConfig: 'local' };</script>\n",
    ),
    "mdi_plus": ("MDI+", ""),
    "gpgam": ("GPGam", ""),
}


def _read(path):
    with open(os.path.join(HERE, path)) as f:
        return f.read()


def shared_head(index_html, title, extra):
    """The index page's <head>, with this page's title and extra scripts.

    pdoc emits no <title>, so one is inserted after the charset meta rather than
    substituted -- otherwise every page would show up untitled in the browser tab.
    """
    head = index_html[index_html.index("<head>"):index_html.index("</head>")]
    title_tag = f"<title>imodels &middot; {title}</title>"
    if "<title>" in head:
        head = re.sub(r"<title>.*?</title>", title_tag, head, flags=re.S)
    else:
        head = head.replace('<meta charset="utf-8">',
                            '<meta charset="utf-8">\n' + title_tag, 1)
    # the index's own canonical link would point every page at the index
    head = re.sub(r'\s*<link rel="canonical".*?>', "", head, flags=re.S)
    return head.rstrip() + "\n" + extra + "</head>"


def shared_sidebar(index_html):
    """The index page's sidebar, with its in-page anchors pointed back at it."""
    start = index_html.index('<nav id="sidebar">')
    end = index_html.index("</nav>", start) + len("</nav>")
    nav = index_html[start:end]
    # `#installation` only resolves on the index itself
    return re.sub(r'href="#', 'href="index.html#', nav)


def main():
    index_html = _read("index.html")
    head = index_html[index_html.index("<head>"):index_html.index("</head>")]
    sidebar = shared_sidebar(index_html)
    for name, (title, extra) in PAGES.items():
        content = _read(os.path.join("pages", f"{name}.html")).strip()
        page = (
            "<!doctype html>\n<html lang=\"en\">\n\n"
            + shared_head(index_html, title, extra)
            + "\n\n<body>\n    <main>\n        <article id=\"content\">\n"
            + content
            + "\n        </article>\n"
            + sidebar
            + "\n    </main>\n\n    <footer id=\"footer\">\n    </footer>\n</body>\n\n</html>\n"
        )
        with open(os.path.join(HERE, f"{name}.html"), "w") as f:
            f.write(page)
        print(f"  wrote {name}.html")


if __name__ == "__main__":
    main()
